language: ruby
bundler_args: --without debug profile extra
rvm:
  - 2.0.0
  - 1.9.2
  - 1.9.3
#  - jruby-18mode
#  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - ree
notifications:
  email:
    recipients:
      - sylvester@keil.or.at
    on_success: change
    on_failure: always
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: 1.8.7
    - rvm: ree
