language: ruby
sudo: false
cache: bundler

matrix:
  include:
  - rvm: 3.0
  - rvm: 2.7
  - rvm: 2.6
  - rvm: 2.5
  - rvm: jruby-19mode

before_install:
  - gem install bundler

install:
    bundle install --without debug profile extra;

script:
    bundle exec rake;

notifications:
  email:
    recipients:
      - sylvester@keil.or.at
    on_success: change
    on_failure: change
